- name: "Remove upgrade label"
  oc_label:
    name: "{{ inventory_hostname }}"
    state: absent
    kind: node
    labels:
    - key: upgrade
  delegate_to: "{{ groups.oo_first_master.0 }}"
- name: "Restore gluster daemonset label"
  oc_label:
    name: "{{ inventory_hostname }}"
    state: add
    kind: node
    labels:
    - key: glusterfs
      value: storage-host
  delegate_to: "{{ groups.oo_first_master.0 }}"

