- import_playbook: docker-service-enable.yml

- hosts: all
  user: root
  tasks:

   - name: Load Docker images for Openshift
     shell: /images//images_{{ IMAGE_VERSION }}/imageload.sh
     when: DOCKER_IMAGE_LOAD | default(false) | bool

