# Main Openshift node cleanup playbook
#
#     To be run after the Openshift uninstall playbooks
#

- import_playbook: yum-uninstall-packages.yml

- import_playbook: uninstall_docker.yml

- import_playbook: uninstall_gluster.yml

- import_playbook: rescan_disk_devices.yml

