# Main Openshift node cleanup playbook
#
#     To be run after the Openshift uninstall playbooks
#

- import_playbook: uninstall_docker_devices.yml

- import_playbook: uninstall_gluster_devices.yml

- import_playbook: rescan_disk_devices.yml

