

- name: Add the group var definitions to inventory
  ansible.builtin.blockinfile:
    path: "{{ INVENTORY_FILE }}"
    marker_begin: "Custom group variables - BEGIN"
    marker_end: "Custom group variables - END"
    block: "{{ item }}"
  with_items:
    - "{{lookup('ansible.builtin.file', '{{ INVENTORY_GROUPS_FILE }}') }}"

