---
# tasks file for kubespray-cluster-onboard
- name: Print the gateway for each host when defined
  ansible.builtin.debug:
    msg:
      - "Company Name: {{ COMPANY }}"

- name: Print the gateway for each host when defined
  ansible.builtin.debug:
    msg:
      - "Inventory_file: {{ INVENTORY_PATH }}"
      - "Company Name: {{ COMPANY }}"
      - "Application Name: {{ APPNAME }}"
      - "Domain: {{ DOMAIN }}"
      - "Cluster Name: {{ CLUSTERNAME }}"


- import_tasks: remove_section.yml

- import_tasks: generate_groups.yml

- import_tasks: add_groups_to_inventory.yml
