#- name: Remove k8scluster section
#  lineinfile: path=/tmp/inventory_stock.yaml
#              state=absent 
#              regexp='k8s-cluster [*]'


- name: Remove k8scluster section
  ansible.builtin.replace:
    path: /tmp/inventory_stock.yaml
#    after: 'k8s-cluster [*]'
#    regexp: '^(.+)$'
#    regexp: ((k8s-cluster:)[\S\s]*|$)
    regexp: '^\s*k8s-cluster:[\S\s]*$'
#    regexp: '^\s*k8s-cluster:.*$'

#- replace:
#        path: /tmp/test.yaml
#        regexp: '^\s*control_center_basic_users:[\S\s]*$'
