
- name: Remove the group var definitions from inventory
  ansible.builtin.blockinfile:
    path: "{{ INVENTORY_PATH }}/inventory_stock.yaml"
    state: absent
    marker_begin: "Custom group variables - BEGIN"
    marker_end: "Custom group variables - END"
    block: ""

- name: Remove k8scluster section
  ansible.builtin.replace:
    path: "{{ INVENTORY_PATH }}/inventory_stock.yaml"
    regexp: '^\s*k8s-cluster:[\S\s]*$'



