- hosts: nodes
  user: root
  tasks:
   - name: Install supporting RPM packages
     yum:
       state: latest
       name: bash-completion, bind-utils, bridge-utils, nfs-utils, git, iptables-services, kexec-tools, net-tools, psacct, sos, wget

   - name: Install Docker if not already present
     yum:
       state: present
       name: docker

   - name: Install Gluster packages
     yum:
       state: latest
       name: glusterfs-fuse

- hosts: masters
  user: root
  tasks:
   - name: Install packages for Openshift masters
     yum:
       state: latest
       name: openshift-ansible, openldap-clients

